services:
  db:
    image: postgres:15-alpine
    container_name: subminder_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: subminder_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - subminder-network
    restart: always

  # --- SERVICE REDIS (Avec Persistance) ---
  redis:
    image: redis:alpine
    container_name: subminder_redis
    # Activation du mode persistant (AOF - Append Only File)
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      # Montage du volume pour que les données survivent au redémarrage
      - redis_data:/data
    networks:
      - subminder-network
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    container_name: subminder_api
    command: npm run dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://user123:password123@db:5432/subminder_db?schema=public
      - DIRECT_URL=postgresql://user123:password123@db:5432/subminder_db?schema=public
      - FRONTEND_URL=http://localhost:3000
      # Connection à Redis via le nom du service
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis # Attend que Redis soit prêt
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - subminder-network

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: subminder_client
    command: npm run dev -- --host
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_API_TARGET=http://api:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - subminder-network
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  # Nouveau volume pour la persistance Redis
  redis_data:

networks:
  subminder-network:
    driver: bridge
